### ISSUE TITLE
Ansible fails after mariadb setup.

### ISSUE THREAD

**Issue by frob** [blastehh/pterodactyl_ansible#2]
Ansible fails after mariadb setup.

When I run the playbook it tells me the db password and then fails when checking the variable `configure_install`

{"msg": "The conditional check 'configure_install is successful' failed. The error was: The 'failed' test expects a dictionary\n\nThe error appears to be in '~/repos/self/pterodactyl_ansible/roles/mariadb/tasks/debian.yml': line 41, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Debian/Ubuntu | Install MariaDB with custom configuration\n  ^ here\n"}

Running grep I see that there is no variable set for `configure_install` anywhere.

**Comment by blastehh** [comment]
The installation process for mariadb changed from the time that I made this part till now.
I have removed that section, fingers crossed it works.

**Comment by frob** [comment]
Testing now, thank you for the quick response.

**Comment by frob** [comment]
This works now.
